name: Portage Auto release linux

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version : '1.22'
      - name: Build portage
        run: go build -o portage main.go
      - name: Package for release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: {{ secrets.GIT_TOKEN }}
          tag: ${{ github.ref }}
          file: .portage
          file_glob: true
