name: Portage Auto release linux

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version : '1.22'
        run: go version
      - name: Build portage
        run: go build -o portage main.go
  release:
    steps:
      - name: Package for release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: {{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: .portage
          file_glob: true